config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  resources :users do
     member do
        get :chat
     end
  end
 resources :messages, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :receiver, class_name: "User"
    validates :body, presence: true
  end
  

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Message", foreign_key: "receiver_id"
  has_one_attached :avatar
  after_create :send_mail


  scope :search_by_email, ->(query, current_user_id) {
    where("email LIKE ?", "#{query}%")
      .where.not(id: current_user_id)
      .order(:email)
  }


  def messages_with(other_user)
    sent_messages.where(receiver: other_user)
                 .or(received_messages.where(sender: other_user))
                 .includes(:sender)
                 .order(created_at: :asc)
  end


  def user_name
    email.split('@')[0].capitalize
  end


  def send_mail
    SendSignUpEmailJob.perform_now(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?



    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
        devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
      @message = current_user.sent_messages.build(message_params)
      if @message.save
        redirect_to chat_user_path(@message.receiver_id)
      else
        flash[:error] = "Message failed to send."
        redirect_to chat_user_path(@message.receiver_id)
      end
    end
  
    private
  
    def message_params
      params.require(:message).permit(:receiver_id, :body)
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = if params[:search].present?
               User.search_by_email(params[:search], current_user.id).includes(:avatar_attachment => [:blob])
             else
               User.where.not(id: current_user.id).order(:email).includes(:avatar_attachment => [:blob])
             end
    @users = @users.paginate(page: params[:page], per_page: 5)
  end
  def chat
    @user = User.find(params[:id])
    @messages = current_user.messages_with(@user)
    @message = Message.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <%=render 'shared/header'%>
    <%= yield %>
    </div>
  </body>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>

app/views/messages/_message.html.erb
<% if message.sender == current_user %>
  <div>
    <p style="text-align: right"><%= message.body %></p>
    <p style="text-align: right; font-size: x-small" ><%= message.created_at.strftime('%b %e, %Y at %I:%M %p') %></p>
  </div>
<% else %>
  <div>
    <p><%= message.body %></p>
    <p style="font-size: x-small"><%= message.created_at.strftime('%b %e, %Y at %I:%M %p') %></p>
  </div>
<% end %>

app/views/shared/_header.html.erb
 <div class="d-flex  align-items-center">
    <% if user_signed_in? %>
      Welcome,&nbsp;<strong><%= current_user.email %></strong>
      <%= link_to 'Edit profile', edit_user_registration_path, class: 'btn btn-primary btn-sm mx-2' %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm mx-2' %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm mx-2' %>
      <%= link_to "Login", new_user_session_path, class: 'btn btn-primary btn-sm mx-2' %>
    <% end %>
  </div><br>
  <hr>

app/views/users/chat.html.erb
<div class="d-flex align-items-center">
  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar, size: '50x50', style: 'border-radius: 50%; margin-right: 10px;' %>
  <% else %>
    <%= image_tag "default.png", size: '50x50', style: 'border-radius: 50%; margin-right: 10px;' %>
  <% end %>
  <h4><i>Chat with <%= @user.user_name %></h4><i>
</div>
<%= render partial: "messages/message", collection: @messages %>
<%= form_with model: Message.new, url: messages_path, remote: true do |form| %>

  <div class="input-group mb-3">
    <%= form.hidden_field :receiver_id, value: @user.id %>
    <%= form.text_field :body, class: "form-control" %>
    <div class="input-group-append">
      <%= form.submit "Send", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<br>
<%= link_to "Back to Users", users_path, class: "btn btn-secondary" %>
<style>
  h2 {
    margin-top: 10px;
    margin-bottom: 20px;
  }
</style>

app/views/users/index.html.erb
<h1>Make a Chit Chat!</h1>
<div class="row">
  <%= form_tag(users_path, method: :get, class: "col-md-6 mb-3") do %>
    <div class="input-group">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search users" %>
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  <% end %>
</div>

<% if @users.any? %>
  <div class="row row-cols-1 row-cols-md-3 g-4">
  <% @users.each do |user| %>
    <div class="col">
      <div class="card h-100">
        <div class="row no-gutters align-items-center">
          <div class="col-md-4 text-center">
            <% if user.avatar.attached? %>
              <%= image_tag(user.avatar, size: '100x100', style: 'border-radius: 50%;') %>
            <% else %>
              <%= image_tag("default.png", size: '100x100', style: 'border-radius: 50%;') %>
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= user.user_name %></h5>
              <p class="card-text"><%= user.email %></p>
            </div>
            <div class="card-footer">
              <%= link_to "Chat", chat_user_path(user), class: "btn btn-success btn-sm" %>
              <% if params[:search].present? %><br>
              <span class="float-end">
                Sent: <%= current_user.sent_messages.where(receiver_id: user.id).count %><br>
                Received: <%= current_user.received_messages.where(sender_id: user.id).count %>
              </span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= will_paginate @users %>
<% else %>
  <p>No users available.</p>
<% end %>